# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    env: 
      MYSQL_URL: ${{ vars.MYSQL_URL }}
      MYSQL_USER: ${{ vars.MYSQL_USER }}
      MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      REPO_VAR: ${{vars.REPO_VAR}}

    steps:
      - uses: actions/checkout@v4
        

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: See env variables
        run: |
          echo "mysql url $MYSQL_URL"
          echo "repo_var $REPO_VAR"
          echo "direct repo_var ${{env.REPO_VAR}}"

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A2A20FBF014F4BF98876AF4125D871EB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8F0122DBC5574CD6A98790467FE0F501 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5F1FCB62AF2E489BA14D7E08C7A758B9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'saleck-test-spring'
          slot-name: 'Production'
          package: '*.jar'
          